# Generated by Django 5.2.4 on 2026-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Housing', 'Housing'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Savings', 'Savings'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Housing', 'Housing'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Savings', 'Savings'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Business', 'Business'), ('Other', 'Other')], max_length=100),
        ),
    ]
